import type { Metadata } from "next";
import "./globals.css";
import { AvenirBook, MontserratMedium, MontserratRegular } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 return (
    <html
      lang="en"
      className={`${AvenirBook.variable} ${MontserratMedium.variable} ${MontserratRegular.variable}`}
    >
      <body className="bg-white antialiased">{children}</body>
    </html>
  );
}